wandb_version: 1

name:
  desc: null
  value: ''
resume:
  desc: null
  value: /data/xikunz/stable-diffusion/debug_logs/2023-06-28T22-31-19_ldm-densenet_all-splitcpp-noema-debug
base:
  desc: null
  value:
  - configs/latent-diffusion/ldm-densenet_all-splitcpp-noema-debug.yaml
train:
  desc: null
  value: true
no_test:
  desc: null
  value: false
project:
  desc: null
  value: null
debug:
  desc: null
  value: true
seed:
  desc: null
  value: 23
postfix:
  desc: null
  value: ''
logdir:
  desc: null
  value: /data/xikunz/stable-diffusion
scale_lr:
  desc: null
  value: false
logger:
  desc: null
  value: true
checkpoint_callback:
  desc: null
  value: true
default_root_dir:
  desc: null
  value: null
gradient_clip_val:
  desc: null
  value: 0.0
gradient_clip_algorithm:
  desc: null
  value: norm
process_position:
  desc: null
  value: 0
num_nodes:
  desc: null
  value: 1
num_processes:
  desc: null
  value: 1
devices:
  desc: null
  value: null
gpus:
  desc: null
  value: 0
auto_select_gpus:
  desc: null
  value: false
tpu_cores:
  desc: null
  value: null
ipus:
  desc: null
  value: null
log_gpu_memory:
  desc: null
  value: null
progress_bar_refresh_rate:
  desc: null
  value: null
overfit_batches:
  desc: null
  value: 0.0
track_grad_norm:
  desc: null
  value: -1
check_val_every_n_epoch:
  desc: null
  value: 1
fast_dev_run:
  desc: null
  value: false
accumulate_grad_batches:
  desc: null
  value: 1
max_epochs:
  desc: null
  value: null
min_epochs:
  desc: null
  value: null
max_steps:
  desc: null
  value: null
min_steps:
  desc: null
  value: null
max_time:
  desc: null
  value: null
limit_train_batches:
  desc: null
  value: 1.0
limit_val_batches:
  desc: null
  value: 1.0
limit_test_batches:
  desc: null
  value: 1.0
limit_predict_batches:
  desc: null
  value: 1.0
val_check_interval:
  desc: null
  value: 1.0
flush_logs_every_n_steps:
  desc: null
  value: 100
log_every_n_steps:
  desc: null
  value: 50
accelerator:
  desc: null
  value: null
sync_batchnorm:
  desc: null
  value: false
precision:
  desc: null
  value: 32
weights_summary:
  desc: null
  value: top
weights_save_path:
  desc: null
  value: null
num_sanity_val_steps:
  desc: null
  value: 2
truncated_bptt_steps:
  desc: null
  value: null
resume_from_checkpoint:
  desc: null
  value: null
profiler:
  desc: null
  value: null
benchmark:
  desc: null
  value: false
deterministic:
  desc: null
  value: false
reload_dataloaders_every_n_epochs:
  desc: null
  value: 0
reload_dataloaders_every_epoch:
  desc: null
  value: false
auto_lr_find:
  desc: null
  value: false
replace_sampler_ddp:
  desc: null
  value: true
terminate_on_nan:
  desc: null
  value: false
auto_scale_batch_size:
  desc: null
  value: false
prepare_data_per_node:
  desc: null
  value: true
plugins:
  desc: null
  value: null
amp_backend:
  desc: null
  value: native
amp_level:
  desc: null
  value: O2
distributed_backend:
  desc: null
  value: null
move_metrics_to_cpu:
  desc: null
  value: false
multiple_trainloader_mode:
  desc: null
  value: max_size_cycle
stochastic_weight_avg:
  desc: null
  value: false
now:
  desc: null
  value: 2023-06-30T12-14-29
hostname:
  desc: null
  value: sscb-a100
pid:
  desc: null
  value: 1617646
screen:
  desc: null
  value: '749715.pts-0.sscb-a100

    '
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.4
    framework: huggingface
    huggingface_version: 4.19.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1688152470.544198
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 54
      - 55
      - 80
      3:
      - 7
      - 16
      - 23
      4: 3.8.16
      5: 0.15.4
      6: 4.19.2
      8:
      - 6
    m:
    - 1: trainer/global_step
      6:
      - 3
