model:
  base_learning_rate: 4.5e-06
  target: ldm.models.autoencoder.VQModel
  params:
    embed_dim: 3
    n_embed: 8192
    monitor: val/rec_loss
    ddconfig:
      double_z: False
      z_channels: 3
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0
    lossconfig:
      target: ldm.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 0
        disc_weight: 0.75
        codebook_weight: 1.0
        n_classes: 8192
data:
  target: ldm.data.base.DataModuleFromConfig
  params:
    batch_size: 16
    num_workers: 1
    wrap: True
    shuffle_val_dataloader: True
    train:
      target: ldm.data.jump_hpa.JUMP_HPA
      params:
        path_to_metadata: /scratch/groups/emmalu/hpa_jump_metadata/jump_metadata.csv
        group: 'train'
        jump_ref_channels: [4, 5, 0] # ER, nucleus, none
        flip_and_rotate: True
        size: 512
        return_info: False
    validation:
      target: ldm.data.jump_hpa.JUMP_HPA
      params:
        path_to_metadata: /scratch/groups/emmalu/hpa_jump_metadata/jump_metadata.csv
        group: 'validation'
        jump_ref_channels: [4, 5, 0] # ER, nucleus, none
        size: 512
        flip_and_rotate: False
        return_info: False
lightning:
  callbacks:
    image_logger:
      target: ldm.callbacks.ImageLogger
      params:
        batch_frequency: 1000
        log_validation: true
        val_batch_frequency: 1000
        max_images: 8
        increase_log_steps: False
        log_first_step: true
        log_on_batch_idx: true
  trainer:
    benchmark: True
    accumulate_grad_batches: 2
    limit_train_batches: 4500
    limit_val_batches: 450
    val_check_interval: 1.0
